name: capstone_pytorch
channels:
  - pytorch
  - pyg
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - pyarrow=5.0.0
  - cudatoolkit=11.3.1
  - numpy=1.21.5
  - pandas=1.4.2
  - torchmetrics=0.8.0
  - wandb=0.12.14
  - rdkit=2020.09.5
  - tensorboard=2.8.0
  - pytorch=1.11.0
  - pyg=2.0.4
  - prettytable=3.2.0
  - scipy=1.8.1
  - transformers=4.11.3
  - pip=21.2.4
  - pip:
    - tqdm==4.64.0
    - streamlit==1.10.0
    - pandas-profiling==3.2.0
    - streamlit-pandas-profiling==0.1.3
    - fair-esm==0.4.2
    - dgllife==0.2.9
    # - dgl==0.8.2        # cpu version
    - dgl-cu113==0.8.2    # gpu version
    - horovod==0.24.3
